version: "3"

services:
  app:
    build:
      context: .
    container_name: go_prometheus
    ports:
      - 8082:8082

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/node_down.yml:/etc/prometheus/node_down.yml
