global:
  scrape_interval: 15s  # 抓取目标实例的频率时间值，默认10s
  scrape_timeout: 10s   # 一次抓取请求超时时间值，默认10s
  evaluation_interval: 1m # 执行配置文件规则的频率时间值, 默认1m

  external_labels:
    monitor: 'proxypool-monitor'



alerting: # 警告设置
  alert_relabel_configs: null


scrape_configs:
  - job_name: go_prometheus_job
    scrape_interval: 2s
    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8082']

  - job_name: go_prometheus
    scrape_interval: 2s
    honor_labels: true
    metrics_path: /metrics_base
    static_configs:
      - targets: ['app:8082']